### ISSUE TITLE
构建版本错误(请求帮助)-label:bug

### ISSUE THREAD

**Issue by XuanXue2008** [DeerGiteaMirror/DeerFolia#1]
我尝试修改官方Folia编译1.21版本
但是我尝试了许久失败了
想请教一下是如何修改文件编译1.21版本的服务端的呢？

**Comment by XuanXue2008** [comment]
还有使用项目dev1.21构建出来的服务器版本为1.20.6

**Comment by xzfg-n15421** [comment]
路过，我之前编译了一份修复刷线机特性的[paper1.21(109)版本](https://wwl.lanzoul.com/iVGKQ261srej)，你如果需要可以先用，我去研究一下这个项](url)

**Comment by xzfg-n15421** [comment]
最新提交可以被构建，一切正常

**Comment by ColdeZhang** [comment]
此项目的 readme 可以作为修改folia的构建参考
建议是全程挂梯子，整个构建流程涉及到 bukkit、spigot、paper他们各自的服务器（自动的），尤其是spigot的仓库不挂梯子完全拉不下来东西

**Comment by ColdeZhang** [comment]
还有就是建议在linux或者mac下操作，windows的话最好在wsl下
我不知道为什么我在我自己的windows设备上永远都没办法正常applyPatches
